name = "service-api"
type = "javascript"
workers_dev = true
compatibility_date = "2022-04-05"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[secrets]
STYTCH_PROJECT_ID = ""
STYTCH_SECRET = ""

[vars]
ENVIORNMENT = "production"
